### ISSUE TITLE
Creación de mi README

### ISSUE THREAD

**Issue by Jassit0** [josefdc/Comunidad-en-GitHub#1]
![Captura de pantalla 2024-07-11 183320](https://github.com/user-attachments/assets/7670a7d0-295f-4f21-9cc5-89281ce2d01c)

**Comment by josefdc** [comment]
Excelente @Jassit0 , puedes agregar algo de tu historia o biografía [README](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme)
