### ISSUE TITLE
Creación de mi README

### ISSUE THREAD

**Issue by PattyLu09** [josefdc/Comunidad-en-GitHub#2]
Hola, Soy Patricia Juárez (PattyLu09), apasionada de la ciencia, curiosa de los juegos de mesa, aprendiz de la acuarela y de la programación. Si quieres formar comunidad donde relaciones Genética-Neurociencias-Ciencias Biomédicas-Programación, o simplemente hacer comunidad, you had me at Hello ;)

**Comment by josefdc** [comment]
Muy bien, me gusta esa introducción @PattyLu09, quedaría muy bien en tu perfil, puedes ver este recurso
[ReadME](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme)
