### ISSUE TITLE
Creación de mi README

### ISSUE THREAD

**Issue by wendyph1209** [josefdc/Comunidad-en-GitHub#3]
![Captura de pantalla 2024-07-11 203719](https://github.com/user-attachments/assets/42c26af0-d642-4bd1-a0fe-23bb52317d52)

**Comment by josefdc** [comment]
Muy bien @wendyph1209  !!

**Comment by josefdc** [comment]
¡Hola @wendyph1209 ! 😊 Tu README es genial y muy amigable, ¡felicidades! 🎉 Me encanta cómo has destacado tu formación en Mujer Digital y Hackademy. Para mejorarlo aún más, podrías considerar agregar una sección sobre tus proyectos destacados y detallar un poco más tus responsabilidades como Analista Junior de Ciberseguridad. ¡Sigue así, estás haciendo un trabajo excelente! 🚀
