### ISSUE TITLE
Mi segundo intento :D

### ISSUE THREAD

**Issue by Jassit0** [josefdc/Comunidad-en-GitHub#4]
Creo que no había entendido la primera instrucción [🤭](https://emojiterra.com/es/cara-con-la-mano-sobre-la-boca/), pero seguí el instructivo que se le envío a @PattyLu09 y creo que ¡lo logré!

![Captura de pantalla 2024-07-11 205810](https://github.com/user-attachments/assets/e3b0e5b5-e51f-4735-ad22-8120f0bd23d1)
![Captura de pantalla 2024-07-11 211517](https://github.com/user-attachments/assets/20bd938d-60ba-4bb9-9ab9-4c77e17a74cc)

Mil gracias por la retro!

**Comment by josefdc** [comment]
Muy bien 👍

**Comment by josefdc** [comment]
¡Hey @Jassit0 ! Qué excelente upgrade, precisamente eso es lo que buscamos, nuestro GitHub suele ser nuestra carta de presentación como devs. Solo un tip, trata de personalizar tu URL de LinkedIn. Puedes ver cómo hacerlo [aquí](https://www.linkedin.com/help/linkedin/answer/87/customizing-your-public-profile-url). ¡Sigue así! 🚀
